include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - local: '.gitlab/ci/*.gitlab-ci.yml'

image:
  name: docker:latest

services:
  - docker:dind

variables:
  DOCKERFILE_PATH: "src/Dockerfile"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA

stages:
  - build
  - test
  - publish
