image:
  name: docker:latest

services:
  - docker:dind

variables:
  DOCKERFILE_PATH: ".gitpod.Dockerfile"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - publish

build:
  script:
    - docker build --tag $CI_REGISTRY_IMAGE/build:$CI_PIPELINE_IID-$CI_COMMIT_SHORT_SHA .
  stage: build
