.pull_docker:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/build:$DOCKER_TAG || true

test-aws:
  extends: .pull_docker
  script:
    - docker run --entrypoint "" --rm $CI_REGISTRY_IMAGE/build:$DOCKER_TAG /bin/sh -c "$(cat ./test/aws.sh)" || exit 1
  stage: test
